# Generated by Django 3.2.8 on 2022-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20220414_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='description',
            field=models.CharField(default='elo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststep',
            name='requirements',
            field=models.CharField(default='siema', max_length=500),
            preserve_default=False,
        ),
    ]
